#!/usr/bin/env bash
set -euo pipefail

# Installs a global `bootstrap` launcher that scaffolds the CURRENT directory
# using this Bootstrapper clone's canonical bootstrap_agent_governance.sh.
#
# The launcher is a thin wrapper with this clone's absolute path baked in, so
# repo updates are picked up immediately and no runtime repo discovery is needed.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANONICAL="$REPO_ROOT/scripts/bootstrap_agent_governance.sh"

BIN_DIR="${BOOTSTRAP_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/bootstrap"

if [[ ! -x "$CANONICAL" ]]; then
  echo "Missing canonical bootstrap script: $CANONICAL" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# bootstrap — scaffold the CURRENT directory with the agent-governance scaffold.
# Generated by scripts/install-bootstrap-command.sh from the Bootstrapper repo.
# Do not edit by hand; re-run the installer to refresh.
#
#   bootstrap                  scaffold the current dir
#   bootstrap --init           scaffold the current dir (explicit synonym)
#   bootstrap --update         update the current dir against this clone
#   bootstrap --check-updates  report scaffold drift for the current dir
#   bootstrap --auto-update    refresh only when missing or behind
#   bootstrap --force-spec     replace BOOTSTRAPPER_SPEC.md
#   bootstrap /path/to/repo    target another dir instead of the current one
#
CANONICAL="$CANONICAL"

if [ ! -x "\$CANONICAL" ]; then
  echo "bootstrap: cannot find \$CANONICAL" >&2
  echo "bootstrap: re-run scripts/install-bootstrap-command.sh from your Bootstrapper clone." >&2
  exit 1
fi

exec "\$CANONICAL" "\$@"
EOF

chmod 0755 "$LAUNCHER"

echo "Installed bootstrap command: $LAUNCHER"
echo "Points at: $CANONICAL"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo "Warning: $BIN_DIR is not on your PATH." >&2
    echo "Add it (e.g. 'export PATH=\"$BIN_DIR:\$PATH\"' in your shell rc) to call 'bootstrap' directly." >&2
    ;;
esac
