#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_ONLY=0

if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
elif [[ "${1:-}" != "" ]]; then
  echo "Usage: scripts/sync-agent-rules.sh [--check]" >&2
  exit 2
fi

RULE_NAMES=(
  "code-review"
  "development-workflow"
  "python-standards"
  "tech-stack"
  "sandbox-permissions"
)

mkdir -p "$ROOT_DIR/rulesets" "$ROOT_DIR/.cursor/rules" "$ROOT_DIR/.claude/rules" "$ROOT_DIR/.codex/rules"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

for name in "${RULE_NAMES[@]}"; do
  if [[ ! -f "$ROOT_DIR/.cursor/rules/$name.mdc" ]]; then
    echo "Missing agent rule file: .cursor/rules/$name.mdc" >&2
    exit 1
  fi
  if [[ ! -f "$ROOT_DIR/.claude/rules/$name.md" ]]; then
    echo "Missing agent rule file: .claude/rules/$name.md" >&2
    exit 1
  fi
done

normalize_rule() {
  local name="$1"
  local src="$2"
  cp "$src" "$TMP_DIR/$name"
}

assert_rule_alignment() {
  local name="$1"
  normalize_rule "cursor-$name" "$ROOT_DIR/.cursor/rules/$name.mdc"
  normalize_rule "claude-$name" "$ROOT_DIR/.claude/rules/$name.md"
  cmp -s "$TMP_DIR/cursor-$name" "$TMP_DIR/claude-$name" || {
    echo "Agent rule divergence detected: $name" >&2
    return 1
  }
}

write_consolidated_ruleset() {
  local output="$1"
  {
    cat <<'EOF'
# Consolidated Agent Ruleset

Generated by `scripts/sync-agent-rules.sh`.

Source of truth for shared governance behavior: this file plus `rulesets/AGENT_BINDINGS.md`.
Edit `.cursor/rules/*` and `.claude/rules/*`, keep them aligned, then re-run the sync script.

EOF
    for name in "${RULE_NAMES[@]}"; do
      printf '## %s\n\n' "$name"
      cat "$ROOT_DIR/.claude/rules/$name.md"
      printf '\n\n'
    done
  } > "$output"
}

write_agent_bindings() {
  local output="$1"
  {
    cat <<'EOF'
# Agent Bindings

Generated by `scripts/sync-agent-rules.sh`.

## Active Rule Files
- `.cursor/rules/*.mdc`
- `.claude/rules/*.md`

## Generated Artifacts
- `.codex/rules/*.md`
- `rulesets/CONSOLIDATED_RULESET.md`

## Binding Rules
- Cursor and Claude rule files must stay semantically aligned.
- Codex mirrors both rule sets.
- If rules conflict, the stricter policy wins.

## Managed Rule Names
EOF
    for name in "${RULE_NAMES[@]}"; do
      printf -- '- `%s`\n' "$name"
    done
  } > "$output"
}

sync_or_check() {
  local expected="$1"
  local target="$2"
  if [[ $CHECK_ONLY -eq 1 ]]; then
    [[ -f "$target" ]] || { echo "Drift: missing mirror file $target" >&2; return 1; }
    cmp -s "$expected" "$target" || { echo "Drift: mirror file differs: $target" >&2; return 1; }
  else
    cp "$expected" "$target"
  fi
}

status=0
for name in "${RULE_NAMES[@]}"; do
  assert_rule_alignment "$name" || status=1
  normalize_rule "codex-$name.md" "$ROOT_DIR/.cursor/rules/$name.mdc"
  normalize_rule "codex-claude-$name.md" "$ROOT_DIR/.claude/rules/$name.md"
  sync_or_check "$TMP_DIR/codex-$name.md" "$ROOT_DIR/.codex/rules/$name.md" || status=1
  sync_or_check "$TMP_DIR/codex-claude-$name.md" "$ROOT_DIR/.codex/rules/claude-$name.md" || status=1
done

write_consolidated_ruleset "$TMP_DIR/CONSOLIDATED_RULESET.md"
write_agent_bindings "$TMP_DIR/AGENT_BINDINGS.md"
sync_or_check "$TMP_DIR/CONSOLIDATED_RULESET.md" "$ROOT_DIR/rulesets/CONSOLIDATED_RULESET.md" || status=1
sync_or_check "$TMP_DIR/AGENT_BINDINGS.md" "$ROOT_DIR/rulesets/AGENT_BINDINGS.md" || status=1

if [[ $status -ne 0 ]]; then
  exit 1
fi

if [[ $CHECK_ONLY -eq 1 ]]; then
  echo "Agent rules, codex mirrors, and rulesets are in sync."
else
  echo "Agent rules synced into .codex/rules and rulesets/."
fi
